---
- hosts: shadowsocks-multiport

  roles:
    - common

    - role: ss-server
      name: "multiport-mannual"
      port_password: "{{ shadowsocks_servers.multiport_mannual.port_password }}"
      enable_udp: "{{ shadowsocks_servers.multiport_mannual.enable_udp }}"
      shadowsocks_provider: "python"
      shadowsocks_enable_multiport: true

    - role: ss-server
      name: "multiport-automatic"
      enable_udp: "{{ shadowsocks_servers.multiport_auto.enable_udp }}"
      shadowsocks_provider: "python"
      shadowsocks_enable_multiport: true
      shadowsocks_enable_multiport_auto_config: true
